### PR TITLE
General AR Events and other stuff

### PR DESCRIPTION
**Pull request by nicolocarpignoli**
* Remove references from ar.js remote repository, now use local paths as default https://github.com/jeromeetienne/AR.js/issues/465
* Emitting events on `window` when camera is initialized and, in case, if camera failed to initialize (e.g. user has not granted permissions) solves: https://github.com/jeromeetienne/AR.js/issues/378
Example of use (check also on `marker-events.html`)
```
window.addEventListener('camera-init', (data) => {
        console.log('camera-init', data);
        // TODO: Add your own code
    })

window.addEventListener('camera-error', (error) => {
        console.log('camera-error', error);
        // TODO: Add your own code e.g. splash screen, message to user, etc.
    })
```

### CODE REVIEW

**Comment by nicolocarpignoli** [comment]
@kalwalt @fernans

Can one of you two (or both) give a little test to this? Also the first part seems more potentially harmful than 'event' one

**Comment by kalwalt** [comment]
@nicolacarpignoli i will take a look at when i have a bit of time, ☺️

**Comment by TimKraemer** [comment]
I'm not on my development device right now, but as far as I can see this probably won't build with `uglify` since it uses `const` and object-shorthands.
Please try if it builds with `make build` and `make minify` - if not, please replace `const` with `var` and object-shorthands like `{ error }` with `{ error: error }`.

**Comment by nicolocarpignoli** [comment]
@TimKraemer absolutely! thanks you were right

**Comment by nicolocarpignoli** [comment]
don't mind conflicts, they are only on build files that will be replaced after the review

**Comment by nicolocarpignoli** [comment]
closes #378 closes #465

**Pull request merged**
