### PR TITLE
Update Three.js docs

### PR DESCRIPTION
**Pull request by Zertz**
**What kind of change does this PR introduce?**

bugfix

**Can it be referenced to an Issue? If so what is the issue # ?**

no

**How can we test it?**

[Generate a custom marker](https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html) with a pattern ratio that is not 0.5

**Summary**

It doesn't work without this undocumented option and the [related docs](https://jeromeetienne.github.io/AR.js/three.js/) have typos in class names.

**Does this PR introduce a breaking change?**

no

### CODE REVIEW

**Comment by nicolocarpignoli** [comment]
Please provide a suitable URL to reproduce the bug. The url you provide has localhsot as host

**Comment by Ryuno-Ki** [comment]
Related to #392?

**Comment by Zertz** [comment]
Updated the link to the production generator and documentation.

Also, note that this is only a documentation issue!

**Comment by nicolocarpignoli** [comment]
looks good! merging

**Pull request merged**
