### PR TITLE
Fixes basic a-frame example

### PR DESCRIPTION
**Pull request by caseyyee**
It looks like the marker used in the couch image no longer works, and I can't find the pattern to the marker.   This PR makes it so that it sets the preset to the hiro marker used in all the other examples.

Also bumps the build, a-frame version and fixes some whitespace.

### CODE REVIEW

**Comment by caseyyee** [comment]
@jeromeetienne review?  The aframe example wasn't working at all, so this fixes that. Please let me know if there are changes you would like to see :)

**Comment by jeromeetienne** [comment]
sorry for hte delay i will check today :)

**Comment by jeromeetienne** [comment]
Merged! thanks!

**Comment by caseyyee** [comment]
thanks!

**Pull request merged**
