### PR TITLE
Implement marker tracking smoothing from @ideolio PR #263

### LINKED ISSUE #311: Jerkiness smoothing
I'm in the middle of the project using AR.js, everything seems to go well, except the heavy jerkiness of the content (video over a poster with marker).

Is there any way to smooth out the motion of the A-camera? Where should I start to look for options in the code? I think simple position averaging over N number of frames would do the job.

### PR DESCRIPTION
**Pull request by andreyrd**
**What kind of change does this PR introduce?**
New feature, marker smoothing.

**Can it be referenced to an Issue? If so what is the issue # ?**
Original PR was #263, and this fixes #311.

**How can we test it?**

**Summary**
Solves the AR experience constantly wiggling because of tiny changes in the marker tracking.
**Does this PR introduce a breaking change?**
No.

**Other information**
This is not my code, the original PR was #263 by @ideolio. We just reimplemented it on a clean code base!
We may want to add a parameter for turning this off / changing settings via parameter instead of constants.

### CODE REVIEW

**Comment by nicolocarpignoli** [comment]
this seems an important changed. @jeromeetienne please take a look

**Comment by andreyrd** [comment]
Do you have suggestions for how something like this should be tested? Does the current testing framework support video comparison? Tracking smoothing happens over time, so not sure how it can be tested :(

**Comment by ideolio** [comment]
Smoothing works by tracking the moving average.

Holding the camera relatively still should result in the 3D scene remaining stationary. 

Once you start moving the camera (e.g around the marker), the algorithm detects large changes in the average and turns off smoothing until the delta is small again.

There are a couple of tuning parameters you can play with for your application. As set you should see smoothing turned off in about a second.

On Oct 30, 2018, at 1:41 PM, Andrey Radchishin <notifications@github.com> wrote:

Do you have suggestions for how something like this should be tested? Does the current testing framework support video comparison? Tracking smoothing happens over time, so not sure how it can be tested :(

**Comment by andreyrd** [comment]
Gotcha, thanks, makes sense how it works.
I'm just wondering how we can set up automatic tests for this.

**Comment by nicolocarpignoli** [comment]
it is not mandatory to have automatic tests, if someone can simply manually test this we can think of a merge

**Comment by nicolocarpignoli** [comment]
no one is available for tests?

**Comment by andreyrd** [comment]
I can refactor this to put it behind a flag, that way it'll be off by default and people can opt-in to testing in the next build, and if no one complains, make it on by default in next major revision?

**Comment by nicolocarpignoli** [comment]
@andreyrd absolutely, thanks!

**Comment by lovisio** [comment]
I check your branch on my project, and I don't see any major change on smoothing anything. 
Thanks anyway.

**Comment by nicolocarpignoli** [comment]
Thanks for the test. For me it's also ok. I merge as it is

**Comment by nicolocarpignoli** [comment]
thank you all!

**Pull request merged**
