### PR TITLE
Address #396 by creating CJS exports

### PR DESCRIPTION
**Pull request by josephrexme**

### CODE REVIEW

**Comment by josephrexme** [comment]
This should help bring a solution to #396

**Comment by evhan55** [comment]
I am happy to help test this with some guidance, I am currently trying to use `ar.js` in my Node project and haven't been able to get it to work.

**Comment by josephrexme** [comment]
@evhan55 you can use https://www.npmjs.com/package/node-ar.js which is a published working version of this pull request https://www.npmjs.com/package/node-ar.js

**Comment by evhan55** [comment]
Thanks! I did get as far as that and the package did load correctly and was available in my node app, so thanks!  Unfortunately, I wasn't working in three.js but was working with A-Frame instead.

**Comment by nicolocarpignoli** [comment]
@josephrexme need to resolve conflicts, please

**Comment by josephrexme** [comment]
@nicolocarpignoli I would but I don't know if this will be merged after I do so. If not, it would be a waste of effort

**Comment by josephrexme** [comment]
Oh I didn't realizing you're maintaining the project now @nicolocarpignoli . I'll make some time to resolve the conflicts

**Comment by janpio** [comment]
This is impossible to merge even with some conflicts fixed, as it reworks the whole project instead of adding the node version in a way that keeps the other code unchanged.

**Comment by josephrexme** [comment]
Oh yes @janpio there was no way for me to achieve making it available for node.js with the way it was all coupled. Perhaps someone else can take on that. This is why I considered making it a separate repo for those who just want to get it to work

**Comment by janpio** [comment]
You best close this PR here then and create a new one just for the README where you link to your repository. (But having an e.g. `node` subfolder that makes it work in the current codebase would be better of course.)

**Comment by josephrexme** [comment]
Thanks @janpio . I will work on the README PR and would have loved to work on extending this with the suggestion of a node subdirectory but I'm currently too occupied to do that.

**Pull request closed without merging**
