### PR TITLE
v3 Release: NFT + code cleaning + doc update and other improvements.

### PR DESCRIPTION
**Pull request by kalwalt**
**⚠️ All PRs have to be done versus 'dev' branch, so be aware of that, or we'll close your issue ⚠️**
From https://github.com/jeromeetienne/AR.js/pull/674#issue-352547279 #674 and #705 
**What kind of change does this PR introduce?**
This PR want to test the new jsartoolkit5 from https://github.com/kalwalt/jsartoolkit5/pull/1 with the new changes especially the NFT part.

### **🖼 This will eventually make AR.js capable of detect and track 2D images.**

https://twitter.com/nicolocarp/status/1204841439160684549

Could be raise some bugs and incompatibilties between the code. It is more a test...
**Can it be referenced to an Issue? If so what is the issue # ?**

From jsartoolkit5 repo:  PR  https://github.com/kalwalt/jsartoolkit5/pull/1
From AR.js issues:

* https://github.com/jeromeetienne/AR.js/issues/544
* https://github.com/jeromeetienne/AR.js/issues/149
* https://github.com/jeromeetienne/AR.js/issues/503
* https://github.com/jeromeetienne/AR.js/issues/420
* https://github.com/jeromeetienne/AR.js/issues/227
* https://github.com/jeromeetienne/AR.js/issues/190
* https://github.com/jeromeetienne/AR.js/issues/185

also, a repo cleaning will help for: https://github.com/jeromeetienne/AR.js/issues/433

**How can we test it?**
Just test the examples and tell us what happens...

**Summary**

**Does this PR introduce a breaking change?**
Nope, it will remove old code, but unnecessary. It will add NFT feature.

**Please TEST your PR before proposing it. Specify here what device you have used for tests, version of OS and version of Browser**

**Other information**
I uploaded the new jsartookit5 libs and build the AR.js libs with makefile. 

**Progress**
- [x] Clean repo before starting the porting
- [x] Import new jsartoolkit5 version, coming with NFT
- [x] Adapt the code (threejs side) to support NFT (emulate what's already done for fiducial markers)
- [x] Fix the rendering of content on AR.js side, for NFT (onMarkerFound function)
- [x] Make it work on mobile
- [x] Enhance resolution in both mobile and desktop
- [x] Check if animations work with NFT. If not, or rendering rate is too high, use interpolation
- [ ] Fix broken pattern marker (content appears shifted after NFT modifies, or maybe even before during the cleaning of the repo)
- [x] Remove all rendering code on the Worker
- [x] Adapt the code (aframe side) to support NFT (emulate what's already done for fiducial markers)
- [x] Create at least one example for threejs + NFT
- [x] Create at least one example for aframe + NFT
- [ ] Change documentation (principal Readme, also with NFT Marker generator + Readmes inside threejs + aframe folders)
- [ ] release version 3 of AR.js

### CODE REVIEW

**Comment by kalwalt** [comment]
@nicolocarpignoli we should re-add the changes in this PR #703 this will solve also the conflicts.

**Comment by kalwalt** [comment]
No, i'm wrong that changes are in the PR, i only deleted the `ar-lean.js` and `ar-lean.min.js` with https://github.com/jeromeetienne/AR.js/pull/722/commits/1455aa8de65603a29e885f0227e96ddba74b8780 because not necessary anymore. We will solve the conflicts while merging this PR.

**Comment by nicolocarpignoli** [comment]
no need for interpolation, animation is working good on both aframe and three.js side.

**Comment by nicolocarpignoli** [comment]
So, cabling the position is something we should take care on jsartoolkti5 (@kalwalt on it).

Here, apart from fixing pattern markers, that is broken (should be something related to cleaning the repo), we have to fix the camera low resolution: now NFT works both on three.js and aframe side but with 480*640 resolution (4:3).
Also has to be fixed on desktop (not so relevant but in general we have to find a more robust way to calculate sizes of canvas and camera stream resolution, according to the viewport).

**Comment by nicolocarpignoli** [comment]
We are almost there! I think that two enhancements can be added in the future, not in v3 release:

* cable positioning of content of NFT inside the core
* cable smoothing on NFT inside the core.

Actually it works defining it on three.js or aframe side.
But it's not that bad, user can have more control this way.
Eventually, we will add defaults in the future.

**Comment by nicolocarpignoli** [comment]
Issue to be added for NFT AFTER release:

* cable positioning of NFT content (to center it) inside the core
* cable smoothing on NFT inside the core
* make NFT work on Desktop too.

**Comment by Marcus5234** [comment]
Wow v3 seems really close to being released. A week is a good estimate? Can't wait for this! Mate, this will cover like 90% of all AR use cases! I can say goodbye to zappar, 8thwall, awe, vuforia, easyar, arcore, arkit. Well, except when I need world tracking, facetracking. superimposition...but those are the 10% arjs won't cover.

**Comment by nicolocarpignoli** [comment]
> Wow v3 seems really close to being released. A week is a good estimate? Can't wait for this! Mate, this will cover like 90% of all AR use cases! I can say goodbye to zappar, 8thwall, awe, vuforia, easyar, arcore, arkit. Well, except when I need world tracking, facetracking. superimposition...but those are the 10% arjs won't cover.

Could be a good estimate :)
We hope to release an useful feature. And hope to get more contributions to make tracking even better. We will see 💪🏻

**Comment by kalwalt** [comment]
> Wow v3 seems really close to being released. A week is a good estimate? Can't wait for this! Mate, this will cover like 90% of all AR use cases! I can say goodbye to zappar, 8thwall, awe, vuforia, easyar, arcore, arkit. Well, except when I need world tracking, facetracking. superimposition...but those are the 10% arjs won't cover.

Yeah it seems that we are on the way! Maybe not a week but we are very optimistic. I'm also very happy, for all the effort that me and @nicolocarpignoli have spent on this, and i hope you all will make awesome project with it!!

**Comment by kalwalt** [comment]
@Marcus5234 and all following this PR, check also this other PR #742 probably this will be the final and definitive Pr with the working code.

**Comment by nicolocarpignoli** [comment]
closing, please refer to: https://github.com/jeromeetienne/AR.js/pull/742

**Pull request closed without merging**
