### PR TITLE
Fix jsartoolkit5 and simplify build

### PR DESCRIPTION
**Pull request by Ouyang-Zhaoxing**
https://trello.com/c/0PKwlTpW

### CODE REVIEW

**Comment by janpio** [comment]
Could we have an explanation of each change please? Some of these could have far reaching implications.

**Comment by Ouyang-Zhaoxing** [comment]
I looked at the file history and found that jerome's scope of modification was very small, including a small portion of the temporary test code that could be confirmed, some of which he had commented out, but seemed to forget to clear them.
The main change is in ARController.prototype._copyImageToHeap, you will find that I cleared the comment code. From the history point of view, jerome repeatedly modified it, but finally re-written one under it, they are similar, obviously this Part of it is left behind.

**Comment by Ouyang-Zhaoxing** [comment]
Minify and replaced ARController.prototype._copyImageToHeap to the mini version.

**Comment by Ouyang-Zhaoxing** [comment]
And I compared the code for the corresponding time period of jsartoolkit5 to make sure I didn't miss anything.

**Comment by Ouyang-Zhaoxing** [comment]
Forgive my lame English, I try to make it easy to understand.

**Comment by Ouyang-Zhaoxing** [comment]
> Could we have an explanation of each change please? Some of these could have far reaching implications.

Forgive my lame English, I try to make it easy to understand.

**Comment by Ouyang-Zhaoxing** [comment]
By the way, I can't change the asm part, it needs to be rebuilt from C++ code, I can't be sure if it fits.

**Pull request closed without merging**
