### PR TITLE
select Camera option

### PR DESCRIPTION
**Pull request by nicolocarpignoli**
Changelog:

- [x] fixed a minor bug in `gps-camera` component
- [x] added a property to `a-scene`: selectCamera. When 'true' it shows a basic UI to let the user select the camera to use. Solves https://github.com/jeromeetienne/AR.js/issues/369, https://github.com/jeromeetienne/AR.js/issues/619, https://github.com/jeromeetienne/AR.js/issues/581, https://github.com/jeromeetienne/AR.js/issues/86, https://github.com/jeromeetienne/AR.js/issues/631, 
https://github.com/jeromeetienne/AR.js/issues/558

### CODE REVIEW

**Comment by nicolocarpignoli** [comment]
@Darrel-Collinsworth @Zaniyar for updates and tests. thanks

**Comment by nicolocarpignoli** [comment]
@Darrel-Collinsworth @Zaniyar can you please test select camera if works?


https://nicolo-carpignoli.herokuapp.com/select-camera/
Marker to scan: https://stemkoski.github.io/AR-Examples/markers/hiro.png

**Comment by ivoras** [comment]
> @Darrel-Collinsworth @Zaniyar can you please test select camera if works?
> 
> https://nicolo-carpignoli.herokuapp.com/select-camera/
> 
> Marker to scan: https://stemkoski.github.io/AR-Examples/markers/hiro.png
> 
> If it gives you error or does not work, please share screenshot of console dev tools of browser.

Blank page in Chrome 78.0.3904.90 on SGS7, Android 8.0.

**Comment by nicolocarpignoli** [comment]
try now

**Comment by Darrel-Collinsworth** [comment]
I can def try this out as well. I'll have a result by sunday. Thank you Nicolo

**Comment by Darrel-Collinsworth** [comment]
i know how to hook up my phone to my computer so I can test it and send inspect screenshots

**Comment by Darrel-Collinsworth** [comment]
> > @Darrel-Collinsworth @Zaniyar can you please test select camera if works?
> > https://nicolo-carpignoli.herokuapp.com/select-camera/
> > Marker to scan: https://stemkoski.github.io/AR-Examples/markers/hiro.png
> > If it gives you error or does not work, please share screenshot of console dev tools of browser.
> 
> Blank page in Chrome 78.0.3904.90 on SGS7, Android 8.0.
> 
> Can you post instructions how to open the dev tools of mobile browser?

It looks like the link for the herokuapp doesn't work currently. was this resolved? and if so can i have a link to a working demo?

**Comment by nicolocarpignoli** [comment]
Link is ok for me is working. Maybe if you don't see anything you got an error. Can I please see logs?

**Comment by Darrel-Collinsworth** [comment]
so the link works for me, but now my camera is displaying a very low resolution. can i see your souce code for the last project you did? did you cange anything on the ar.js 2.0.5?

**Comment by jamess922** [comment]
> It switched to my front camera, but it didn't let me switch again to my 3rd camera (standard focal length) it toggled to the camera facing me and the button disappeared.

Me too

**Comment by nicolocarpignoli** [comment]
Actually the behaviour is the following:

- show switch camera button if property is enabled on a-scene component AND if available cameras are > 1

- clicking on switch camera button makes the camera switch.

- as soon as the 'camera cycle' is finished, the camera button is now hidden. this because currently there was a bug that prevents to 'return' to a camera already opened. I cleaned the stream but still no results. As for now, I don't have much time to enhance this.

Could you please look if with the other cameras (other than default) the AR works? the 3d content shows?

thanks

if you'd like to help and enhance it, the modified code is on this PR

**Comment by Darrel-Collinsworth** [comment]
I'm still new to github, how would I be able to clone the repo with this fix to take a look and see if I can enhance it?

**Comment by nicolocarpignoli** [comment]
Clone the repo first, is the green button on the right corner of the repository homepage. Then you have to switch, on local machine, to this branch, do your modifies, push them and make a PR from your branch-your repo against this branch and this pr repo. Sent from my Huawei phone-------- Original Message --------Subject: Re: [jeromeetienne/AR.js] V2.1.0 (#661)From: Darrel Collinsworth To: "jeromeetienne/AR.js" CC: Nicolò Carpignoli ,Author I'm still new to github, how would I be able to clone the repo with this fix to take a look and see if I can enhance it?

**Comment by Zaniyar** [comment]
@nicolocarpignoli Your herokuapp is showing this behaviour on my phone:

Display first-camera found
Show "Switch camera" button
on click it iterates through "available" cameras..  but for me it doesn't really find the right cameras, it is showing only once a zoomed back camera, then it shows 3 times the front camera and then the button disappears. 

For me the origin problem (wrong camera/ zoomed in camera) is not solved yet.

**Comment by nicolocarpignoli** [comment]
Sad to hear that. I honestly don't know how to 'reach' your 'right' camera as those are the ones available with `device.kind === 'videoinput'`.
Maybe they are not exposed to the broswer.

Is this modify useful for somebody? otherwise I'm just thinking to drop it

@Zaniyar if you find online an example or codepen that can iterate through camera and let you pick the right one, please let us know. At this point, I'm not even sure it's possible..

**Comment by Zaniyar** [comment]
@nicolocarpignoli if I run `navigator.mediaDevices.enumerateDevices().then(x=>console.log(x))` on my phone, I got 5 videoinputs. 4 of them are "facing back" only 1 is "facing front"

**Comment by nicolocarpignoli** [comment]
check the example console.log, I have added a log for all enumerateDevices

**Comment by Zaniyar** [comment]
on the herokuapp? there I don't have any console.logs about how many devices.

**Comment by nicolocarpignoli** [comment]
> on the herokuapp? there I don't have any console.logs about how many devices.

try this one: https://codepen.io/nicolocarpignoli/pen/KKwzRdJ

**Comment by ivoras** [comment]
The latest one (try this one: https://codepen.io/nicolocarpignoli/pen/KKwzRdJ) opens the correct (back) camera on my SGS7, Chrome 78.0.3904.108 (which didn't work with "real" AR.js code), but the CHANGE CAMERA button switches to a white rectangle.

**Comment by nicolocarpignoli** [comment]
If someone has time to bring this forward, it will solve problems with devices with multiple cameras.
Otherwise the temporary solution is to use Firefox, that seems to prompt for all the cameras and make you select the right one.

Anyway, It's possible to start from code on this PR and make a new one (this one has also an obsolete branch name, we have now AR.js v2.1.4).

Unfortunately I do not have time right now. If anyone is willing to help i'm happy to give an hand.

**Comment by harisadam** [comment]
Brave browser also works on Android, so looks like the issue is not chromium related, but Chrome.
We can help with tests on android phones around the office (∼10).

**Comment by harisadam** [comment]
@nicolocarpignoli I started working on a fix and reviewed your code.

If I understand correcly, component-anchor.js would be responsible for handling the camera selection(init function), and threex-artoolkitsource.js (https://raw.githubusercontent.com/jeromeetienne/AR.js/65ca04fe4d5643abae3d66d4a5471607f503849b/three.js/src/threex/threex-artoolkitsource.js _initSourceWebcam function) would be for setting the deviceId and start the video.

What do you think, if I write a my own camera selection code avoiding component-anchor.js and setting window.availableCameras would _initSourceWebcam be able to select the right source?

**Comment by nicolocarpignoli** [comment]
yes it should be the same, best thing is to try :)

**Comment by nicolocarpignoli** [comment]
@harisadam don't know if this helps you, but here's another approach by another guy; https://github.com/jeromeetienne/AR.js/issues/619

**Comment by nicolocarpignoli** [comment]
@harisadam have you done some progress?

**Comment by nicolocarpignoli** [comment]
this PR will be re opened (a new one) when work on this will be more clear. Anyone feel free to open a similar one I would like to partecipate

**Comment by narmeenm94** [comment]
> If someone has time to bring this forward, it will solve problems with devices with multiple cameras.
> Otherwise the temporary solution is to use Firefox, that seems to prompt for all the cameras and make you select the right one.
> 
> Anyway, It's possible to start from code on this PR and make a new one (this one has also an obsolete branch name, we have now AR.js v2.1.4).
> 
> Unfortunately I do not have time right now. If anyone is willing to help i'm happy to give an hand.

Unfortunately, neither Firefox, Samsung Browser, nor chrome work on Samsung galaxy note 10+, any solution for the same issue?

**Pull request closed without merging**
