### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Rechi86**
**What kind of change does this PR introduce?**
Documentation update for the Babylon.js version

**Summary**
Added the info for the custum marker + a tip on clearing the local storage (which was a pitfall for me) after changing the baseURL

### CODE REVIEW

**Comment by jeromeetienne** [comment]
Thanks!

Can you add a comment explaining around "This is clearly a temporary kludge, and i would love if somebody provide a pull request to make it tunable."

Just to make it clear :)

**Comment by ZoltanVeres** [comment]
@jeromeetienne Wouldn't it also make sense to create an issue with a "Help wanted" tag?

**Comment by nicolocarpignoli** [comment]
@Rechi86 could you please resolve conflicts?

**Comment by nicolocarpignoli** [comment]
https://github.com/jeromeetienne/AR.js/issues/362

**Pull request closed without merging**
