### PR TITLE
Update the Makefile and some other things

### PR DESCRIPTION
**Pull request by ghost**
**What kind of change does this PR introduce?**
Fix Makefile and update some other things.
**Can it be referenced to an Issue? If so what is the issue # ?**
[jsartoolkit5](https://github.com/artoolkit/jsartoolkit5)
I think artoolkit.min.js already contains artoolkit.api.js.
**How can we test it?**
No.
**Summary**
Removed a wrong build command from Makefile.
**Does this PR introduce a breaking change?**
No.
**Other information**
No.

### CODE REVIEW

**Comment by janpio** [comment]
What is that new file `three.js/examples/vendor/three.js/build/three-r100.js` about?

**Comment by kalwalt** [comment]
What is the state of this PR ? @janpio @nicolocarpignoli  think this PR was done by a deleted user... so we can close this. I would make another PR for a newer threejs version.

**Comment by janpio** [comment]
Yes, I didn't really understand what this tried to achieve anyway. @nicolocarpignoli will delete this when he sees this.

**Comment by nicolocarpignoli** [comment]
Yes

**Pull request closed without merging**
