### PR TITLE
THREEx.ArMarkerControls Smoothing

### PR DESCRIPTION
**Pull request by ideolio**
Experiment to smooth matrix entries over time to reduce jitter.
Updates to THREEx.ArMarkerControls and debounce in animation loop

To try:

print: https://ideolio.com/files/ar/markers/ideolio-ar-1.pdf

go to on phone/tablet: https://ideolio.com/go#plant?tid=5eb6b13a06
click eye icon top right

First pull request, not sure if done properly...

dp

-------------------------------------------------------------------------

**animation loop in main code**

        function animate(){                                                                         // update artoolkit on every frame
            var
                renderReqd;
            if (active) {                                                                           // if slow on some devices use timer approach
                renderReqd = arToolkitContext.update(arToolkitSource.domElement);
                if ($_3DDisplay.camera.visible) {                                                   // smooth over momentary losses of marker sync
                    arDebounce = 0;
                    renderReqd = renderReqd || !$_3DDisplay.scene.visible;
                    $_3DDisplay.scene.visible = true;
                } else {
                    if (arDebounce >= 15) {                                                             // don't hide immediately wait for a number of frames to avoid flashing on/off if sync lost
                        $_3DDisplay.scene.visible = false;
                        renderReqd = true;
                    } else {
                        arDebounce++;
                    }
                }
                renderReqd && $_3DDisplay.renderer.render($_3DDisplay.ARmarkerRoot.parent,$_3DDisplay.camera);              // parent is scene
                requestAnimationFrame(animate);
            }
        }

----------------------------------------------------------------------------

**updates to THREEx.ArMarkerControls**

    this.debounceMatrices = [];                                                         // last DEBOUNCE_COUNT modelViewMatrix
    this.DEBOUNCE_COUNT = 10;                                                           // average over this many
    this.AVERAGE_MATRIX_TOLERANCE = .01;                                                // max allowable distance from current matrix entry to average
    this.AVERAGE_MATRIX_THRESHOLD = 5;                                                  // if at least this many entries (out of 16) exceed AVERAGE_MATRIX_TOLERANCE then moving

THREEx.ArMarkerControls.prototype.updateWithModelViewMatrix = function(modelViewMatrix){
    var markerObject3D = this.object3d;

    // mark object as visible
    markerObject3D.visible = true

    if( this.context.parameters.trackingBackend === 'artoolkit' ){
        // apply context._axisTransformMatrix - change artoolkit axis to match usual webgl one
        var tmpMatrix = new THREE.Matrix4().copy(this.context._artoolkitProjectionAxisTransformMatrix)
        tmpMatrix.multiply(modelViewMatrix)

        modelViewMatrix.copy(tmpMatrix)
    }else if( this.context.parameters.trackingBackend === 'aruco' ){
        // ...
    }else if( this.context.parameters.trackingBackend === 'tango' ){
        // ...
    }else console.assert(false)

    if( this.context.parameters.trackingBackend !== 'tango' ){

        // change axis orientation on marker - artoolkit say Z is normal to the marker - ar.js say Y is normal to the marker
        var markerAxisTransformMatrix = new THREE.Matrix4().makeRotationX(Math.PI/2)
        modelViewMatrix.multiply(markerAxisTransformMatrix)
    }

    // change markerObject3D.matrix based on parameters.changeMatrixMode
    if( this.parameters.changeMatrixMode === 'modelViewMatrix' ){
        markerObject3D.matrix.copy(modelViewMatrix)
    }else if( this.parameters.changeMatrixMode === 'cameraTransformMatrix' ){
    //        markerObject3D.matrix.getInverse( modelViewMatrix )
        // *** start change
        var
            sum,
            i,j,
            renderReqd = false,
            averages,                                                                                   // average values for matrix over last DEBOUNCE_COUNT
            exceedsAverageTolerance = 0;

        this.debounceMatrices.push(modelViewMatrix.elements.slice());                                   // add latest

        if (this.debounceMatrices.length < (this.DEBOUNCE_COUNT+1)) {
            markerObject3D.matrix.getInverse( modelViewMatrix );                                        // not enough for average

        } else {
            this.debounceMatrices.shift();                                                              // remove oldest entry
            averages = [];

            for (i in modelViewMatrix.elements) {                                                       // loop over entries in matrix
                sum = 0;
                for (j in this.debounceMatrices) {                                                      // calculate average for this entry
                    sum += this.debounceMatrices[j][i];
                }
                averages[i] = sum/this.DEBOUNCE_COUNT;
                if (Math.abs(averages[i] - modelViewMatrix.elements[i]) >= this.AVERAGE_MATRIX_TOLERANCE) {  // check how many elements vary from the average by at least AVERAGE_MATRIX_TOLERANCE
                    exceedsAverageTolerance++;
                }
            }

            if (exceedsAverageTolerance >= this.AVERAGE_MATRIX_THRESHOLD) {                             // if moving (i.e. at least AVERAGE_MATRIX_THRESHOLD entries are over AVERAGE_MATRIX_TOLERANCE)
                for (i in modelViewMatrix.elements) {                                                   // then update matrix values to average, otherwise, don't render to minimize jitter
                    modelViewMatrix.elements[i] = averages[i];
                }
                markerObject3D.matrix.getInverse( modelViewMatrix );
                renderReqd = true;                                                                      // render required in animation loop
            }
        }
        // *** end change (see return below)
    }else {
        console.assert(false)
    }

    // decompose - the matrix into .position, .quaternion, .scale
    markerObject3D.matrix.decompose(markerObject3D.position, markerObject3D.quaternion, markerObject3D.scale)

    // dispatchEvent
    this.dispatchEvent( { type: 'markerFound' } );
    return renderReqd;                                                                                  // ***
}

### CODE REVIEW

**Comment by ZoltanVeres** [comment]
@jeromeetienne Not sure what's happening in this branch.
How can we have a PR from dev branch to the master branch?
Notice how all changes you did appearing in this PR as well.
@ideolio Can you please create another PR with the changes you suggested?
I think we need to close this PR.

**Comment by ideolio** [comment]
I would be pleased to do so.

New on GitHub. Could you point me to where I should create the PR?

Regards,

dp

On Dec 9, 2017, at 3:03 PM, Zoli Veres <notifications@github.com> wrote:

@jeromeetienne <https://github.com/jeromeetienne> Not sure what's happening
in this branch.
How can we have a PR from dev branch to the master branch?
Notice how all changes you did appearing in this PR as well.
@ideolio <https://github.com/ideolio> Can you please create another PR with
the changes you suggested?
I think we need to close this PR.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jeromeetienne/AR.js/pull/263#issuecomment-350501903>,
or mute the thread

**Comment by ZoltanVeres** [comment]
@ideolio  Fork the AR.js repository do the changes `THREEx.ArMarkerControls`
I suppose you extracted this from your source code.
Commit the changes and push to your forked AR.js repository.
You can create a Pull Request directly from the the web on the Github site. 
As always you can Google the steps for more details.

**Comment by dreinstein10** [comment]
Hi @ideolio, 
sorry if this is an obvious question but where do you add the "function animate()" code?   Where do the "active" and "$_3DDisplay" variables come from?

I'm trying to implement your modifications but I'm still learning to code and I'm not sure how to do it.
Is there any sample code I can look at ?

Thanks in advance

**Comment by ideolio** [comment]
Start by understanding a threejs example and then have a look at one of Jerome's examples. e.g.

https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/basic.html

Look for requestAnimationFrame. When that is invoked, you should call the animate function.

"active" is a boolean that you can set when no longer using AR so the requestAnimationFrame function does nothing.

"$_3DDisplay" is a namespace we use to manage 3D code that interfaces to threejs. 
$_3DDisplay.camera is the threejs camera
$_3DDisplay.renderer is the threejs renderer 
etc

All the best,

dp

**Comment by javismiles** [comment]
If this fixes jerkiness, its very important, Can somebody merge this? thank you

**Comment by javismiles** [comment]
If we  use  aframe-ar, where would this have to be fixed? thank you

**Comment by andreyrd** [comment]
We were able to successfully able to implement this in our project by overriding `ARjs.MarkerControls = THREEx.ArMarkerControls = ...`.

Should I open a new pull request with a clean implementation of this on an up-to-date `master`?

**Comment by loelkes** [comment]
> We were able to successfully able to implement this in our project by overriding `ARjs.MarkerControls = THREEx.ArMarkerControls = ...`.
> 
> Should I open a new pull request with a clean implementation of this on an up-to-date `master`?

Yes please.

**Pull request closed without merging**
