### PR TITLE
set correct gps-camera selector for gps-entity-place 

### PR DESCRIPTION
**Pull request by smuddy**
**⚠️ All PRs have to be done versus 'dev' branch, so be aware of that, or we'll close your issue ⚠️**

**What kind of change does this PR introduce?**
The PR fixes the issue, that aframe creates a camera in the DOM and the component gps-entity-place finds this instead of the real gps-camera.

**Can it be referenced to an Issue? If so what is the issue # ?**
Issue: "GeoAR: camera.components['gps-camera'] is undefined #626"

**How can we test it?**
insert `<a-entity aframe-injected="" camera="" look-controls="" position="" rotation="" wasd-controls=""></a-entity>` into your `<a-scene>`, if it`s not created by aframe. Then add your `<a-camera gps-camera></a-camera>`.
`gps-entity-place` should allways select the gps-camera.

**Summary**
see above

**Does this PR introduce a breaking change?**
no

**Please TEST your PR before proposing it. Specify here what device you have used for tests, version of OS and version of Browser**
Tested in a cordova app in android (Samsung Galaxy S9)

**Other information**
-

### CODE REVIEW

**Comment by nicolocarpignoli** [comment]
I have aligned dev to master (dev was behind). Now you should check if your PR is against dev branch, changes should be way more than current ~50 files

**Comment by nicolocarpignoli** [comment]
@smuddy please check this PR files as it should be only 1 change not ~50

**Comment by smuddy** [comment]
Hi, the current work was part of a research for using AR.js in a bigger Project for my company. Next week the new sprint starts and then, I will make a new PR with the change. 
I must confess this is the first time I work on an open source git project. What is the usual way for this? My plan is to pull the current dev branch to my fork, making the changes and make an new PR from my dev branch to yours.

I still have some other improvements I could push:

- Smoothing compass data to avoid jitter
- move position calculation of the marker from init() to tick() that fixes the issue, that markers doesn‘t have the correct position if I insert them before the gps data is available als also allows position update while moving
- rotating the markers so they point directly to the camera
- considering all camera rotation values, not only the y-axis for better AR experience

**Comment by nicolocarpignoli** [comment]
@smuddy Wow, this is great! Thank you so much, those addition will be of great great help.

Your workflow for PR is absolutely perfect. Can't wait to see your works. 

Thanks again!

**Comment by smuddy** [comment]
I close this PR. The promised changes will be requested from my companys GitHub account.

**Comment by nicolocarpignoli** [comment]
@smuddy hi there , any news? 😊

**Comment by smuddy** [comment]
Hi,
most of the changes are not useful for comon use, because they mostly are workarounds for make the framework running in angular/cordova considering iOS restrictions.

But currently I'm struggeling with fov Problem in the portrait mode. Perhaps I will open a seperate issue for this.

**Pull request closed without merging**
