### PR TITLE
fixing portrait mode

### PR DESCRIPTION
**Pull request by pikilipita**
changes on 2 functions to get correct rotation and aspect ratio of models in portrait mode

### CODE REVIEW

**Comment by jeromeetienne** [comment]
WOW thanks, i will test that, but if it works it is great! i had this bug for a long time :(

**Comment by pikilipita** [comment]
Yeah, a long time issue, I really needed portrait mode on XR.+, so I had no choice but to fix it ;)

**Comment by AndreaMonzini** [comment]
@pikilipita @jeromeetienne  do you have the A-Frame Build to test the fix? Thank you !

**Comment by pikilipita** [comment]
Sorry, I'm not using A-Frame so did not applied the patch to it. You have to wait for  jeromeetienne  to review this commit

**Comment by Adolar13** [comment]
Ammended it like yout did. Works for me, thanks pikilipita!

**Comment by LeviBerciu** [comment]
Thanks @pikilipita ! Your fix works like a charm :)

**Comment by jeromeetienne** [comment]
Merged! thanks for fixing this :)

**Comment by javismiles** [comment]
friends, this was  a great fix, anybody has any ideas for #249 ? its a basic one, being able to click on an specific element (which works great on aFrame by itself), all best

**Comment by makslevental** [comment]
this doesn't fix it on ios devices but this does :)

```
            function onResize() {
                arToolkitSource.onResizeElement()
                arToolkitSource.copyElementSizeTo(renderer.domElement)
                setTimeout(function(){
                    arToolkitSource.onResizeElement()
                    arToolkitSource.copyElementSizeTo(renderer.domElement)
                }, 500);
            }
```

**Comment by jeromeetienne** [comment]
@makslevental interresting! where is this onResize you are speaking about ?

**Comment by makslevental** [comment]
@jeromeetienne https://github.com/jeromeetienne/AR.js/blob/146d301c86f641dc3b392954ff526bce06972af7/three.js/examples/basic.html#L70

**Comment by hoktok** [comment]
All the new branches after fixing the portrait mode do not work aframe using a-anchor and custom markers. Does anyone have an working version? Thank you.

**Comment by tom-bruce** [comment]
@stefanluchian Interesting, do you know of a fix for this?

**Comment by stefanluchian** [comment]
No, but I look forward to test the fixes in issues #678 and #750 regarding this problem.
Also something new seems to be available: https://github.com/AR-js-org/AR.js/. Not sure what exactly is different comparing to this repo.

**Comment by nicolocarpignoli** [comment]
The one you linked is the repo where you should open issues/PRs. It will be the new repository for AR.js, owned by an organization and not left alone like the current one.

Migration is happening, we are in the process these days.

**Pull request merged**
