### PR TITLE
Adding links for Trello and Gitter to dev branch.

### PR DESCRIPTION
**Pull request by thor-brickman**
**What kind of change does this PR introduce?**
Just adding two lines to the Status section of the Readme for the Gitter lobby and Trello board.

** Can it be referenced to an Issue? If so what is the issue # ?**
#506

**How can we test it?**

Just click em. :-)

**Summary**

**Does this PR introduce a breaking change?**
Nope

**Other information**

### CODE REVIEW

**Comment by nicolocarpignoli** [comment]
I think this way that 2 links are not very visible, but it is ok to put them on the 'Status' section.
Maybe it is better to move the entire 'Status' section above, e.g. after the 'What marker based means' section.
What do you think about that?

Also, when this is 'validated', it will be great if you can align master and dev readme with another PR

**Comment by thor-brickman** [comment]
I was going for the minimum changes at first, but your comment is dead on and brings up some other thoughts.

There is already a link to the Trello board from the bottom of the Index, which I left in place because too much information is usually better than none.

Perhaps a larger and more efficient change would be to add a 'Community' section to the readme right after the Related Projects section, then consolidate links to various other repos/discussions/etc there?

And I will absolutely submit a PR for the same change in the master once the dev changes are in place. :-)

Thanks!
Thor

**Comment by nicolocarpignoli** [comment]
ok for me, you can go with the Community section :)

**Comment by thor-brickman** [comment]
Ok, moved things to the new Community heading.

**Pull request merged**
