### PR TITLE
Temporary fix. NPM support with UMD pattern.

### PR DESCRIPTION
**Pull request by sasha240100**
**This PR is related to issue #7**.

I wrapped sources with [umd pattern](https://github.com/umdjs/umd/blob/master/templates/returnExports.js#L40) to make it work with common module systems _(AMD, CommonJS, ...)_.

**NOTE:** I removed some assertions in https://github.com/sasha240100/AR.js/commit/1447523df24b1367afab127304a33d070e8b1c8d in order to make it work. They can be added back after moving to ES6/ES2016+.

**Tested on:**
- [x] Node (through webpack build).
- [x] Browser

### CODE REVIEW

**Comment by jeromeetienne** [comment]
thanks, a lot of the file got modified tho..

did you change the tabulation or something ?

**Comment by sasha240100** [comment]
@jeromeetienne Seems like my editor(Atom) did it for me. Do we have a specific linter || codestyle to follow?

**Comment by sasha240100** [comment]
@jeromeetienne I personally like XO code style with [my personal config](https://github.com/WhitestormJS/whitestorm.js/blob/beta/package.json#L88). It shows code style errors in runtime and can be easily set up for this project.

**Comment by jeromeetienne** [comment]
to change it in this pull request, makes it hard to see what are the changes...

Can you do without changing tab/space ?

**Comment by sasha240100** [comment]
@jeromeetienne Made some fixes in code style + updated to latest code from your `master`. The only major change i did is that i added UMD pattern code at the beginning & end of each file.

**Comment by jeromeetienne** [comment]
it seems that the tab/space are still changeed, no ?

**Comment by sasha240100** [comment]
@jeromeetienne 

----

**Please, merge it before you will add more changes, because it will only add more work to me and i will need to make all things from scratch((**

----

**Comment by sasha240100** [comment]
@jeromeetienne Any updates?

**Comment by sasha240100** [comment]
@jeromeetienne Fixed identation `2 spaces -> tabs`

**Pull request closed without merging**
