### PR TITLE
fix custom marker

### PR DESCRIPTION
**Pull request by rondagdag**
code was missing to use custom marker, this will use patternUrl as specified in the documentation.

### CODE REVIEW

**Comment by rondagdag** [comment]
this might be related to #168.

**Comment by AndresCuervo** [comment]
Awesome, @jeromeetienne it would be great if this could merge soon, custom markers are a widely used feature of the library and this fix seems to handle fixing it in the `aframe-ar` bridge!

**Comment by karanganesan** [comment]
Hey @jeromeetienne it would be nice if you merge this PR with master ✌️👌

**Comment by rdub80** [comment]
Hey @jeromeetienne, I tested every other configuration, this is the only way I get custom markers work for me, hoping for a merge soon ✌️

**Comment by AndresCuervo** [comment]
@jeromeetienne this PR seems complete, please merge soon as it's been sitting here for quite a while!

**Comment by rdub80** [comment]
@jeromeetienne - a merge ETA for this please - I would like to realize some kickass client work with custom markers without having a "hacked" version of your code as a fallback. Please merge this PR with master ✌️👌

**Comment by jeromeetienne** [comment]
@rondagdag thanks a lot for doing the work.

sorry about the delay to merge.

**Comment by mattGraphics** [comment]
Hi @jeromeetienne, should this work now? I have downloaded the files in the last day or so but custom markers still not working for me. Is there something special I need to do, is it working for others?

**Comment by ZeeCoder** [comment]
I think @jeromeetienne didn't release it in the end.

**Comment by mattGraphics** [comment]
Ahh, thank you @ZeeCoder that helps.

**Comment by BobAleena** [comment]
I'm not sure I understand 'didn't release it in the end' -- it says that he merged it in both in this thread as well as at the top of the repo. What additional should I be looking at so that it is clearer about what the current state is?

screen shot 2018-03-04 at 11 12 38 am

**Comment by rdub80** [comment]
This means @jeromeetienne merged and ran build but did not run a *release* yet, so we are still on [1.5.1 from August 2017](https://github.com/jeromeetienne/AR.js/releases) which doesn't contain the updated code.

**Comment by mattGraphics** [comment]
Hey @jeromeetienne  @ZeeCoder  @rdub80  : do you have any insight into why the updated code hasn't been released yet? I'm so keen to use AR with my students, but without custom markers working it's of no use. I've tried so many suggestions over the past few weeks, but with no luck.

It looks like some people are able to create and use custom markers (for example evry.one are making really cool custom markers as of a few days ago: https://codepen.io/staus/pen/oEOJpq ), but none of them have ever worked for me.

**Comment by mattGraphics** [comment]
I've solved the issue I had with custom markers so in case this helps anyone else: the custom marker doesn't work for me unless it is on a server (in my case my github repository), it didn't work when referenced locally on my computer. Once I had uploaded the custom marker to github and changed the 'url' on the web page accordingly it worked fine.

**Comment by kalwalt** [comment]
@mattGraphics it should works on the dev fork, Have you tried it?

**Comment by mattGraphics** [comment]
Hi @kalwalt I am very new to github but now I have set up a website here, it all works perfectly, thank you!

**Pull request merged**
