### PR TITLE
Y position for gps entity place

### PR DESCRIPTION
**Pull request by wreszelewski**
**⚠️ All PRs have to be done versus 'dev' branch, so be aware of that, or we'll close your issue ⚠️**

**What kind of change does this PR introduce?**
A new feature.

**Can it be referenced to an Issue? If so what is the issue # ?**
#600 

**How can we test it?**

Just add an yPosition parameter to some gps-entity-place and check that the position on y axis changed.

**Summary**

PR adds a parameter yPosition to gps-entity-place and allows to change positions of object on y-axis while in location mode.

**Does this PR introduce a breaking change?**
The newly introduced parameter is optional and if you don't specify it gps-entity-place will behave in the same way as before change. 

**Please TEST your PR before proposing it. Specify here what device you have used for tests, version of OS and version of Browser**

Smartphone: Xiaomi Mi A1, Android 9, Chrome v79.0.3945.116

**Other information**

### CODE REVIEW

**Comment by nicolocarpignoli** [comment]
@wreszelewski Hi, I will give it a look! Have you already tested it on a mobile device?
I think I tried to do this way some times ago but never worked. Maybe I remember wrong :)
Will try it!

**Comment by wreszelewski** [comment]
@nicolocarpignoli - Yes, I've tested it on mobile and definately I can see that each object with yPosition assigned changed its position on y-axis. However there may be some requirements that I don't know yet :) that make this solution wrong.

**Comment by nicolocarpignoli** [comment]
I have tested but does not work for me. 

```
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>GeoAR.js demo</title>
    <script src="https://aframe.io/releases/0.9.2/aframe.min.js"></script>
    <script src='../../build/aframe-ar.js'></script>
    <script>
        THREEx.ArToolkitContext.baseURL = 'https://raw.githack.com/jeromeetienne/ar.js/master/three.js/'
    </script>
</head>

<body style='margin: 0; overflow: hidden;'>
    <a-scene
        vr-mode-ui="enabled: false"
		embedded
		arjs='sourceType: webcam; sourceWidth:1280; sourceHeight:960; displayWidth: 1280; displayHeight: 960; debugUIEnabled: false;'>

        <a-sphere color="red" scale="70 70 70" gps-entity-place="latitude: 44.698600; longitude: 10.627660;"></a-box>
        <a-box color="yellow" scale="80 80 80" gps-entity-place="yPosition: 100; latitude: 44.494690; longitude: 11.314760;"></a-box>
        <a-camera gps-camera rotation-reader>
		</a-camera>
	</a-scene>
</body>
```

This is my example (please not the use of aframe < version 1, as version 1 gives problem, I have opened an issue for that).

Two things:

* the yPosition in which unit is?
* can you provide a code that works for you (an example)? So i Can see

In the example above,  I see the two contents (the sphere and the box) at the same y height

**Comment by nicolocarpignoli** [comment]
I'm finding strange behaviour. I have to investigate. If you please can provide me one or two snippet of code of examples that work for you, would be great, so I can understand

**Comment by wreszelewski** [comment]
The code that you pasted works for me. I changed only the position, scale of object so that they are of similar size. The position that I entered is a little away for me, because if it is exactly where I am I'm inside the sphere and I can't see it, while box is exactly over me.

What kind of strange behaviour do you mean?

The code:
`<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>GeoAR.js demo</title>
    <script src="https://aframe.io/releases/0.9.2/aframe.min.js"></script>
    <script src='/aframe-ar.js'></script>
    <script>
        THREEx.ArToolkitContext.baseURL = 'https://raw.githack.com/jeromeetienne/ar.js/master/three.js/'
    </script>
</head>

<body style='margin: 0; overflow: hidden;'>
    <a-scene
        vr-mode-ui="enabled: false"
		embedded
		arjs='sourceType: webcam; sourceWidth:1280; sourceHeight:960; displayWidth: 1280; displayHeight: 960; debugUIEnabled: false;'>

        <a-sphere color="red" scale="50 50 50" gps-entity-place="latitude: 52.325759; longitude: 20.9448667;"></a-sphere>
        <a-box color="yellow" scale="50 50 50" gps-entity-place="yPosition: 90; latitude: 52.325759; longitude: 20.9448667;"></a-box>
        <a-camera gps-camera rotation-reader>
        </a-camera>
    </a-scene>
</body>
`

What I see:
83485509_622255011909507_5343245341233774592_n

**Comment by nicolocarpignoli** [comment]
Can you please share with me an example with at least 3 entities:

1 with yPosition 
1 with another yPosition, higher than the first one
1 without yPosition defined

That works for you. I will test it and tell you

thank you

**Comment by nicolocarpignoli** [comment]
ps. don't mind conflicts I will solve myself when everything will be good/tested

**Comment by nicolocarpignoli** [comment]
Can you please re-open this PR on the new dev branch? thank you

**Comment by nicolocarpignoli** [comment]
No need to make another pr: now should work on latest version, see here for details:
https://github.com/jeromeetienne/AR.js/issues/600

**Pull request closed without merging**
